### ISSUE TITLE
"No module named pymunk._chipmunk_cffi_abi"

### ISSUE THREAD

**Issue by Derpford** [viblo/pymunk#161]
When including pymunk, I get an error:
```
 File ".../pymunk/pymunk/__init__.py", line 58, in <module>
    from . import _chipmunk_cffi
  File ".../pymunk/pymunk/_chipmunk_cffi.py", line 3, in <module>
    from pymunk._chipmunk_cffi_abi import ffi, lib, lib_path
ModuleNotFoundError: No module named 'pymunk._chipmunk_cffi_abi'
```
This is using latest git as a submodule.

**Comment by viblo** [comment]
Im pretty sure there are no code changes that can cause this since the last release. Can you provide some more info: OS, Python version and how you run it exactly?

**Comment by Derpford** [comment]
Currently running OpenSuse Linux, with Python 3. I'm including Pymunk into a Pygame project, which I'm running from the command line.

**Comment by viblo** [comment]
Did you compile chipmunk first?

**Comment by Derpford** [comment]
I didn't realize I needed to. My bad.

**Comment by Derpford** [comment]
While compiling using the instructions in the readme, I get the following error:
```
> python setup.py build_ext --inplace                                                                                                                                                                                    ~/memelords/pymunk

Traceback (most recent call last):
  File "setup.py", line 207, in <module>
    class bdist_wheel_universal_extension(bdist_wheel):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
```

**Comment by viblo** [comment]
Seems like there was a bug so that the setup.py build_ext command required the wheel package even while it shouldnt. I have committed a fix for this you can try out.

For the first error you got (before compiling), could you paste the full error here? Its supposed to be a message printed out that tells you to compile chipmunk if it cant find the library file.

**Comment by Derpford** [comment]
The full text of the error:
```
> python3 main.py                                                                                                                                                                                                               ~/memelords
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import actors, rooms, hud
  File "/home/dbrz/memelords/rooms.py", line 3, in <module>
    import pymunk.pymunk as pymunk
  File "/home/dbrz/memelords/pymunk/pymunk/__init__.py", line 58, in <module>
    from . import _chipmunk_cffi
  File "/home/dbrz/memelords/pymunk/pymunk/_chipmunk_cffi.py", line 3, in <module>
    from pymunk._chipmunk_cffi_abi import ffi, lib, lib_path
ModuleNotFoundError: No module named 'pymunk._chipmunk_cffi_abi'
```
Gonna go try that patch now. Thanks for your help!

**Comment by Derpford** [comment]
OK, Chipmunk compiles cleanly, but I'm still getting what appears to be the same error.

**Comment by viblo** [comment]
Ah, now I think I know the problem. If you inlucde pymunk as a folder directly you have to modify the path to make it work. 

So instead of doing import `pymunk.pymunk as pymunk` try adding the top pymunk folder to the path variable:
```
import sys
sys.path.insert(1, 'pymunk')
import pymunk
```

**Comment by Derpford** [comment]
That works! Now I just have to fix my own buggy code. Thanks for all the help!

**Comment by viblo** [comment]
Nice! I made a small update to the documentation, so hopefully it will be easier for other people with the same issues in the future.
